ollama.api.url=http://localhost:11434/api/generate
ollama.model=llama3.2:1b
ollama.base.url=http://localhost:11434

spring.datasource.url=jdbc:mysql://localhost:3306/AIAgent
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true